#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL 
	CREATE USER "$BB_USER_LOGIN" WITH PASSWORD '$BB_USER_PASSWORD';
	CREATE DATABASE "$BB_DB_NAME" OWNER "$BB_USER_LOGIN";
	ALTER DATABASE "$BB_DB_NAME" SET TIME ZONE 'UTC'; 
	GRANT ALL PRIVILEGES ON DATABASE "$BB_DB_NAME" TO "$BB_USER_LOGIN"; 
	GRANT CREATE ON DATABASE "$BB_DB_NAME" TO "$BB_USER_LOGIN";

	GRANT pg_read_all_settings TO "$BB_USER_LOGIN";
	GRANT pg_read_all_stats TO "$BB_USER_LOGIN";
	GRANT pg_read_server_files TO "$BB_USER_LOGIN"; 
	GRANT SELECT ON TABLE pg_extension TO "$BB_USER_LOGIN";
	GRANT CREATE ON DATABASE postgres TO "$BB_USER_LOGIN";

	--because we can create extension pg_cron only in BB_DB_NAME 
	\c "$BB_DB_NAME"
	CREATE EXTENSION IF NOT EXISTS pg_cron; 
	GRANT USAGE ON SCHEMA cron TO "$BB_USER_LOGIN";
	
	GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cron TO "$BB_USER_LOGIN";
	ALTER DEFAULT PRIVILEGES IN SCHEMA cron GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$BB_USER_LOGIN";
        ALTER DEFAULT PRIVILEGES IN SCHEMA cron GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$BB_USER_LOGIN";

	CREATE EXTENSION IF NOT EXISTS dblink;
	CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

	\c "$BB_DB_NAME" "$BB_USER_LOGIN"

	CREATE SCHEMA data AUTHORIZATION "$BB_USER_LOGIN";
EOSQL

