#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL 
	CREATE USER "$BB_USER_LOGIN" WITH PASSWORD '$BB_USER_PASSWORD';
	CREATE DATABASE "$BB_DB_NAME" OWNER "$BB_USER_LOGIN";
	ALTER DATABASE "$BB_DB_NAME" SET TIME ZONE 'UTC'; 
	GRANT ALL PRIVILEGES ON DATABASE "$BB_DB_NAME" TO "$BB_USER_LOGIN"; 
	GRANT CREATE ON DATABASE "$BB_DB_NAME" TO "$BB_USER_LOGIN";

	GRANT pg_read_all_settings TO "$BB_USER_LOGIN";
	GRANT pg_read_all_stats TO "$BB_USER_LOGIN";
	GRANT pg_read_server_files TO "$BB_USER_LOGIN"; 
	GRANT SELECT ON TABLE pg_extension TO "$BB_USER_LOGIN";
	GRANT CREATE ON DATABASE postgres TO "$BB_USER_LOGIN";

	CREATE EXTENSION IF NOT EXISTS dblink;
	CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

	\c "$BB_DB_NAME" "$BB_USER_LOGIN"

	CREATE SCHEMA data AUTHORIZATION "$BB_USER_LOGIN";
EOSQL

