# Разрешаем локальные подключения с доверием (например, для репликации)
local   all             all                                     peer
local   replication     all                                     peer

# Локальные соединения через IPv4 (для контейнеров в одной сети Docker)
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Контейнеры в той же сети Docker (172.18.0.0/16)
host    all             all             172.30.0.0/16           md5

# Доверяемые IP-адреса для удалённых соединений через порт 5432
host    all             all             1.2.3.4/32          md5
host    all             all             1.2.3.4/32       md5
host    all             all             1.2.3.4/32         md5
